name: Build and Deploy Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: |
          cp README.md ../readme-backup
          rm -rf *
          mkdir _pages
          cp ../readme-backup _pages/index.md

      - uses: hydephp/action@v0.7.1
        with:
          deploy-to: "pages"
