name: Build Standalone

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-standalone-binary:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the standalone
      run: php build/build-bin.php --git

    - name: Push commited changes
      run: git push
